name: deploy master to dev env

on:
  push:
    branches:
      - 'master'
      - '8.context'

jobs:
  docker:
    runs-on: ubuntu-20.04
    environment:
      name: development
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
          cache: 'npm'
      -
        run: mkdir -p /home/runner/.npm
        continue-on-error: true
      -
        run: node --version
      -
        run: npm i --legacy-peer-deps
      -
        run: npm run build:dev
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      -
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      -
        name: Echo short SHA
        run: echo ${{ steps.vars.outputs.sha_short }}
      -
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./ 
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/lipinav/sb3000/app:${{ steps.vars.outputs.sha_short }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            NODE_ENV=development
            CLIENT_ID=${{ secrets.CLIENT_ID }}
            REDDIT_SECRET=${{ secrets.REDDIT_SECRET }}
            REDIRECT_URI=${{ secrets.REDIRECT_URI }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: docker run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull ghcr.io/lipinav/sb3000/app:${{ steps.vars.outputs.sha_short }}
            docker rm -f sb3000-dev
            docker run -d --name sb3000-dev -p 570:3000 ghcr.io/lipinav/sb3000/app:${{ steps.vars.outputs.sha_short }} run dev-noneenv
